### ISSUE TITLE
DurandKerner method not working

### ISSUE THREAD

**Issue by hovkaren** [albertodev01/equations#51]
DurandKerner method to get roots for this polynomial not working 

`f(x) = x^5-15*x^4+85*x^3-225*x^2+274*x-120 = (x-1)(x-2)(x-3)(x-4)(x-5)`

Output is

 ```
3.000000000032681 - 1.638722097643922e-11i
 1.0000000000074334 + 4.808957393459463e-12i
 3.9999999999569584 - 8.640728872144793e-11i
 4.999999999971171 - 2.950621409822605e-11i
 1.9999999999677651 - 9.063695579567508e-12i
```

But should be 

```
1
2
3
4
5
```

**Comment by albertodev01** [comment]
Hello 🙂 

The output is correct because the Durand-Kerner **approximates** the roots of equations. There is no formula that gives you exact solutions to a polynomial equation whose degree is 5 or higher. This is the class documentation

```dart
/// The algorithm requires an initial set of values to find the roots. This
/// implementation generates some random values if the user doesn't provide
/// initial points to the algorithm.
///
/// Note that this algorithm does **NOT** always converge. To be more clear, it
/// is **NOT** true that for every polynomial, the set of initial vectors that
/// eventually converges to roots is open and dense.
final class DurandKerner extends Algebraic with MathUtils {
```

Note that:

 - `3.000000000032681 - 1.638722097643922e-11i` approximates to 3 + 0i
 - `1.0000000000074334 + 4.808957393459463e-12i` approximates to 1 + 0i
 - `3.9999999999569584 - 8.640728872144793e-11i` approximates to 4 + 0i
 - `4.999999999971171 - 2.950621409822605e-11i` approximates to 5 + 0i
 - `1.9999999999677651 - 9.063695579567508e-12i` approximates to 2 + 0i

So you get the expected results, more or less. You have to approximate the real part and the imaginary part. For example, `9.063695579567508e-12` is 0.000000000009063695... so a very small number that is close to 0.

This is just how root finding algorithm work, there is no exact solution

**Comment by hovkaren** [comment]
Is it make sense round roots?

**Comment by albertodev01** [comment]
Yes 🙂 if you round roots, you will get an approximated result
